apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000        # service port
      targetPort: 5000  # The target port on which the container listens
      nodePort: 30005
